apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-application-controller
          env:
            - name: ARGOCD_APP_CONTROLLER_REPLICAS
              value: "1"