apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1
resources:
  - resources/namespace.yaml
  - patch/argocd-cm.yaml
  - patch/argocd-server-deployment.yaml
  - patch/argocd-repo-server-deployment.yaml
  - patch/argocd-applications-controller-statefulset.yaml