apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1
resources:
  - kustomization-install/resources/namespace.yaml
  - kustomization-install/patch/argocd-cm.yaml
  - kustomization-install/patch/argocd-server-deployment.yaml
  # - kustomization-install/patch/argocd-repo-server-deployment.yaml
  # - kustomization-install/ patch/argocd-applications-controller-statefulset.yaml